name = "glistix_gleeunit"
version = "1.1.0"
licences = ["Apache-2.0"]
description = "A fork of gleeunit for Glistix's Nix target"
target = "nix"
gleam = ">= 0.33.0"
repository = { type = "github", user = "glistix", repo = "gleeunit" }
links = []

[javascript.deno]
allow_read = [
  "gleam.toml",
  "test",
  "build",
]

[dependencies]
# Run 'git submodule add --name stdlib -- https://github.com/glistix/stdlib external/stdlib'
# to clone Glistix's stdlib patch to the local path specified below. This is needed so stdlib
# will work on the Nix target. Hex dependents will use the stdlib version specified below,
# in [glistix.preview.hex-patch], instead.
gleam_stdlib = { path = "./external/stdlib" }

[dev-dependencies]

# The [glistix.preview] namespace contains useful settings which will be needed
# during Glistix beta. In the future, it's likely these won't be necessary
# anymore.
[glistix.preview]
# If you're patching a package using a local dependency/Git submodule and you
# get a local dependency conflict error, add it to the list below.
local-overrides = ["gleam_stdlib"]

# The section below allows publishing your package to Hex despite having
# local dependencies, by declaring that you depend on another Hex package
# instead.
# This is needed to be able to patch stdlib etc. locally during development
# and at the same time publish to Hex without the patch.
# The section below should only be used for this purpose. Please do not abuse
# this feature, as it is mostly a temporary workaround while Gleam doesn't have
# a proper dependency patching system.
[glistix.preview.hex-patch]
gleam_stdlib = ">= 0.32.0 and < 2.0.0"
